#!/bin/bash +ex

npm run build

echo "stein.sh" > dist/CNAME

git add dist

git commit --message "feat: add build files"

git subtree split --branch gh-pages --prefix dist

git push --force origin gh-pages
